# Generated by Django 5.0.2 on 2024-03-20 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='first_name',
            field=models.OneToOneField(default=5, on_delete=django.db.models.deletion.CASCADE, to='members.profile'),
            preserve_default=False,
        ),
    ]
