# Generated by Django 5.0.2 on 2024-03-20 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_tweet_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='first_name',
        ),
    ]
