# Generated by Django 5.0.2 on 2024-05-09 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_profile_follows'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_pic',
        ),
    ]
